### ISSUE TITLE
xiaomi Redmi k30 pro pmos no works

### ISSUE THREAD

**Issue by yuweiyuan8** [SekaiMoe/pmos_ci_build#3]
Has postmarket os been tested on the Redmi k30 pro, when I was testing, Then crash, this is about 6.11 kernel problem, I would like to ask, Redmi k30 pro touchscreen and GPU can be fixed.

**Comment by SekaiMoe** [comment]
?

**Comment by yuweiyuan8** [comment]
你好，postmarket os在红米k30pro上不工作，开机花屏，然后死机

**Comment by SekaiMoe** [comment]
> 你好，postmarket os在红米k30pro上不工作，开机花屏，然后死机

Full dmesg log pls

**Comment by yuweiyuan8** [comment]
![Uploading mmexport1726142128811.png…]()

**Comment by yuweiyuan8** [comment]
![Uploading mmexport1726142128811.png…]()

**Comment by yuweiyuan8** [comment]
![Uploading mmexport1726142128811.png…]()

**Comment by SekaiMoe** [comment]
？
